# Generated by Django 5.1.1 on 2024-10-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20180517_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flexcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='heroacquaintance',
            name='detractors',
            field=models.ManyToManyField(related_name='+', to='entities.hero'),
        ),
        migrations.AlterField(
            model_name='heroacquaintance',
            name='friends',
            field=models.ManyToManyField(related_name='+', to='entities.hero'),
        ),
        migrations.AlterField(
            model_name='heroacquaintance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='heroacquaintance',
            name='main_anatagonists',
            field=models.ManyToManyField(related_name='+', to='entities.villain'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='villain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
